#!/usr/bin/env bash
# script to install load balancer HAproxy  1.5 or greater
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 447390-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 447390-web-02 52.87.219.99 check\n\tserver 447390-web-01 100.26.226.194 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
