#!/usr/bin/env bash
# script to install load balancer HAproxy  1.5 or greater
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 1563-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 1563-web-02 34.73.79.20:80 check\n\tserver 1563-web-01 34.138.109.1:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
